use aikit_core::{ResourceRef, AikitError};
use aikit_store::{AikitHome,encounter::{EncounterStore,context::*}};
fn session()->ResourceRef{ResourceRef::parse("agent-session/test").unwrap()}
fn scope()->ContextScope{ContextScope{project:"project:test".into(),agent_session:Some(session())}}
fn selection(start:u64,text:&str)->ContextSelection{ContextSelection{source_ref:"central:source:test.md".into(),source_revision:Some("r1".into()),source_project:Some("test".into()),title:"test.md".into(),owner:"Central".into(),binding_id:"source-pane".into(),text:text.into(),anchor:SelectionAnchor::Text{start,end:start+text.encode_utf16().count() as u64},working_copy:false,captured_at:"2026-09-20T00:00:00Z".into()}}
fn add(store:&EncounterStore,scope:&ContextScope,basis:u64,start:u64,text:&str)->PreparedContext{store.edit_context(scope,basis,ContextMutation::Add{selection:Box::new(selection(start,text)),expression:None}).unwrap()}
fn store()->(tempfile::TempDir,EncounterStore){let root=tempfile::tempdir().unwrap();let home=AikitHome::at(root.path().join("aikit"));let store=EncounterStore::open(&home).unwrap();(root,store)}
fn expectation(c:&PreparedContext)->ContextExpectation{ContextExpectation{scope:c.scope.clone(),revision:c.revision,digest:c.digest.clone(),reviewed:c.items.iter().map(|x|x.id.clone()).collect()}}
#[test] fn repeated_passages_have_distinct_exact_identity(){let (_root,s)=store();let first=add(&s,&scope(),0,0,"same");let two=add(&s,&scope(),first.revision,10,"same");assert_eq!(two.items.len(),2);assert_ne!(two.items[0].id,two.items[1].id);let again=add(&s,&scope(),two.revision,10,"same");assert_eq!(again.items.len(),2);}
#[test] fn unicode_ranges_use_utf16_and_reject_wrong_units(){let (_root,s)=store();let item=add(&s,&scope(),0,3,"a🙂é");assert_eq!(item.items.len(),1);let mut bad=selection(0,"🙂");bad.anchor=SelectionAnchor::Text{start:0,end:1};assert!(bad.validate().is_err());}
#[test] fn native_vak_roundtrip_and_no_ql_dependency(){let (_root,s)=store();let c=s.edit_context(&scope(),0,ContextMutation::Add{selection:Box::new(selection(0,"text")),expression:Some("@1 central:source:test.md / @4 project:test".into())}).unwrap();assert_eq!(aikit_core::resource::parse_resolve_expression(&c.items[0].canonical_expression).unwrap(),c.items[0].expression);}
#[test] fn malformed_expression_leaves_revision_unchanged(){let (_root,s)=store();assert!(s.edit_context(&scope(),0,ContextMutation::Add{selection:Box::new(selection(0,"text")),expression:Some("(".into())}).is_err());assert_eq!(s.prepared_context(&scope()).unwrap().revision,0);}
#[test] fn context_cas_refuses_lost_update(){let (_root,s)=store();add(&s,&scope(),0,0,"text");assert!(s.edit_context(&scope(),0,ContextMutation::Clear).is_err());assert_eq!(s.prepared_context(&scope()).unwrap().items.len(),1);}
#[test] fn legacy_prompt_cannot_drop_prepared_context(){let (_root,s)=store();add(&s,&scope(),0,0,"text");s.set_draft(&session(),0,"Explain this").unwrap();let mut dispatched=false;assert!(s.submit(&session(),1,|_|{dispatched=true;Ok(())}).is_err());assert!(!dispatched);}
#[test] fn exact_snapshot_is_delivered_and_receipted(){let (_root,s)=store();let c=add(&s,&scope(),0,0,"untrusted <instructions> 🙂");s.set_draft(&session(),0,"Explain this").unwrap();let mut payload=String::new();s.submit_context(&session(),1,Some(&expectation(&c)),|text|{payload=text.into();Ok(())}).unwrap();assert!(payload.contains("untrusted <instructions> 🙂"));assert!(payload.contains("canonical_expression"));assert_eq!(s.prepared_context(&scope()).unwrap().items.len(),0);let view=s.view(&session(),None).unwrap();assert_eq!(view["prepared_context_receipts"][0]["items"][0]["source_ref"],"central:source:test.md");assert_eq!(view["blocks"][0]["text"],"Explain this");}
#[test] fn stale_context_refuses_before_provider_effect(){let (_root,s)=store();let old=add(&s,&scope(),0,0,"one");add(&s,&scope(),old.revision,5,"two");s.set_draft(&session(),0,"Explain").unwrap();let mut sent=false;assert!(s.submit_context(&session(),1,Some(&expectation(&old)),|_|{sent=true;Ok(())}).is_err());assert!(!sent);}
#[test] fn failed_dispatch_retains_draft_and_selections(){let (_root,s)=store();let c=add(&s,&scope(),0,0,"text");s.set_draft(&session(),0,"Explain").unwrap();assert!(s.submit_context(&session(),1,Some(&expectation(&c)),|_|Err(AikitError::new("provider.failed","offline"))).is_err());assert_eq!(s.draft(&session()).unwrap().text,"Explain");assert_eq!(s.prepared_context(&scope()).unwrap().items.len(),1);}
#[test] fn project_preparation_needs_no_agent_and_adopts_atomically(){let (_root,s)=store();let project=ContextScope{project:"project:test".into(),agent_session:None};let c=add(&s,&project,0,0,"text");assert!(s.adopt_context(&scope(),0,0).is_err());let adopted=s.adopt_context(&scope(),0,c.revision).unwrap();assert_eq!(adopted.items.len(),1);assert!(s.prepared_context(&project).unwrap().items.is_empty());}
#[test] fn other_sessions_and_projects_do_not_receive_context(){let (_root,s)=store();let c=add(&s,&scope(),0,0,"text");let other=ResourceRef::parse("agent-session/other").unwrap();s.set_draft(&other,0,"Explain").unwrap();assert!(s.submit_context(&other,1,Some(&expectation(&c)),|_|Ok(())).is_err());let project=ContextScope{project:"project:other".into(),agent_session:Some(session())};assert!(s.prepared_context(&project).unwrap().items.is_empty());}
#[test] fn oversize_is_refused_not_truncated(){let (_root,s)=store();let text="a".repeat(256*1024+1);assert!(s.edit_context(&scope(),0,ContextMutation::Add{selection:Box::new(selection(0,&text)),expression:None}).is_err());assert_eq!(s.prepared_context(&scope()).unwrap().revision,0);}
