use std::env;
use std::path::Path;
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-env-changed=AIKIT_BUILD_SOURCE_REVISION");
    println!("cargo:rerun-if-env-changed=AIKIT_BUILD_SOURCE_DIRTY");
    embed_first_party_registry();

    if let Ok(revision) = env::var("AIKIT_BUILD_SOURCE_REVISION") {
        if !revision.trim().is_empty() {
            println!(
                "cargo:rustc-env=AIKIT_BUILD_SOURCE_REVISION={}",
                revision.trim()
            );
            println!(
                "cargo:rustc-env=SUITE_BUILD_REVISION={}",
                short_revision(revision.trim())
            );
            let dirty = env::var("AIKIT_BUILD_SOURCE_DIRTY").unwrap_or_else(|_| "0".into());
            println!("cargo:rustc-env=AIKIT_BUILD_SOURCE_DIRTY={dirty}");
            return;
        }
    }

    let manifest = env::var_os("CARGO_MANIFEST_DIR").unwrap_or_default();
    let revision = Command::new("git")
        .arg("-C")
        .arg(&manifest)
        .args(["rev-parse", "HEAD"])
        .output()
        .ok()
        .filter(|output| output.status.success())
        .map(|output| String::from_utf8_lossy(&output.stdout).trim().to_owned())
        .filter(|value| !value.is_empty());

    if let Some(revision) = revision {
        println!("cargo:rustc-env=AIKIT_BUILD_SOURCE_REVISION={revision}");
        println!(
            "cargo:rustc-env=SUITE_BUILD_REVISION={}",
            short_revision(&revision)
        );
        let dirty = Command::new("git")
            .arg("-C")
            .arg(&manifest)
            .args(["status", "--porcelain", "--untracked-files=no"])
            .output()
            .ok()
            .filter(|output| output.status.success())
            .is_some_and(|output| !output.stdout.is_empty());
        println!(
            "cargo:rustc-env=AIKIT_BUILD_SOURCE_DIRTY={}",
            if dirty { "1" } else { "0" }
        );
    }
}

/// The suite-wide short build identity stamped into `--version`.
fn short_revision(revision: &str) -> String {
    revision.chars().take(12).collect()
}

/// Embed the committed first-party registry into the binary.
///
/// The registry at the repo root is CI-validated source (`builtin_registry.rs`,
/// `scripts/verify-native-skills.py`); the shipped binary carries it
/// byte-for-byte — paths, permission bits and contents — so a fresh
/// `AIKIT_HOME` can be materialised on any machine (`src/first_party.rs`).
/// Permission bits travel because hook capsule entries are executed directly
/// and need the executable bit to survive materialisation.
fn embed_first_party_registry() {
    let manifest = env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo");
    let registry_root = Path::new(&manifest).join("../../registry");
    println!("cargo:rerun-if-changed={}", registry_root.display());

    let mut files = Vec::new();
    collect_files(&registry_root, &registry_root, &mut files);
    files.sort();
    assert!(
        !files.is_empty(),
        "the committed first-party registry should contain files"
    );

    let mut generated =
        String::from("// Generated by build.rs from the committed registry/ tree — do not edit.\n");
    generated.push_str(
        "#[rustfmt::skip]\npub static FIRST_PARTY_REGISTRY: &[(&str, u32, &[u8])] = &[\n",
    );
    for relative in &files {
        let relative = relative.to_string_lossy().replace('\\', "/");
        let mode = file_mode(&registry_root.join(&relative));
        generated.push_str(&format!(
            "    (\"{relative}\", {mode}, include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
             \"/../../registry/{relative}\"))),\n"
        ));
    }
    generated.push_str("];\n");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo");
    let destination = Path::new(&out_dir).join("first_party_registry.rs");
    if let Err(error) = std::fs::write(&destination, generated) {
        panic!("could not write {}: {error}", destination.display());
    }
}

/// Every regular file under `top`, as paths relative to it. `current` is the
/// directory being walked and starts at `top`.
fn collect_files(top: &Path, current: &Path, files: &mut Vec<std::path::PathBuf>) {
    let entries = match std::fs::read_dir(current) {
        Ok(entries) => entries,
        Err(error) => panic!("could not read {}: {error}", current.display()),
    };
    for entry in entries {
        let entry = match entry {
            Ok(entry) => entry,
            Err(error) => panic!("could not read entry in {}: {error}", current.display()),
        };
        let path = entry.path();
        let file_type = match entry.file_type() {
            Ok(file_type) => file_type,
            Err(error) => panic!("could not stat {}: {error}", path.display()),
        };
        if file_type.is_dir() {
            collect_files(top, &path, files);
        } else if file_type.is_file() {
            let relative = path
                .strip_prefix(top)
                .expect("walked paths sit under the top root")
                .to_path_buf();
            files.push(relative);
        }
    }
}

/// Permission bits of `path` (unix) or a read-only fallback elsewhere.
fn file_mode(path: &Path) -> u32 {
    let metadata = match std::fs::metadata(path) {
        Ok(metadata) => metadata,
        Err(error) => panic!("could not stat {}: {error}", path.display()),
    };
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        metadata.permissions().mode() & 0o777
    }
    #[cfg(not(unix))]
    {
        if metadata.permissions().readonly() {
            0o444
        } else {
            0o666
        }
    }
}
